### ISSUE TITLE
Crash in PrivatedExecuteAsync

### ISSUE THREAD

**Issue by taylorchasewhite** [KeyserDSoze/Rystem.OpenAi#70]
### Describe the bug

I recently upgraded our projects to .NET 8 and upgraded various packages along the way. In doing so, we also started getting a crash in `Rystem.OpenAi.HttpClientExtensions.PrivatedExecuteAsync`. I wasn't able to step into the source code to see exactly where.

Here's our stack trace:

```
----- Exception -----
System.NullReferenceException: Object reference not set to an instance of an object.
   at Rystem.OpenAi.HttpClientExtensions.PrivatedExecuteAsync(HttpClient client, String url, HttpMethod method, Object message, Boolean isStreaming, CancellationToken cancellationToken)
   at Rystem.OpenAi.HttpClientExtensions.ExecuteWithResponseAsync[TResponse](HttpClient client, String url, Object message, HttpMethod method, OpenAiConfiguration configuration, CancellationToken cancellationToken)
   at Rystem.OpenAi.Chat.ChatRequestBuilder.ExecuteAsync(Boolean autoExecuteFunction, CancellationToken cancellationToken)
   at OurGov.Data.Services.ArtificialIntelligence.LanguageProcessing.Base.ChatGptServiceBase.Execute(String caller, String systemMessage, List`1 history, CancellationToken cancellationToken, ChatMessage[] excludeMessages) in /src/Data/Services/OurGov.Data.Services.ArtificialIntelligence/LanguageProcessing/Base/ChatGptServiceBase.cs:line 71
```

### To Reproduce

See consuming code example.

### Code snippets

```ASP.NET
Here's how we consume the service/`ChatRequestBuilder`

if(history.Count == 0)
	throw new ArgumentNullException(nameof(history));

ChatRequestBuilder request = Chat
	.RequestWithSystemMessage(systemMessage)
	.WithModel(ChatModelType.Gpt35Turbo)
	.WithTemperature(0.1)
	.WithUser($"{_name}: {caller}");

foreach(ChatMessage? message in history)
{
	// If there was a failure, abort the whole conversation
	if(message is null)
		return null;

	if(!excludeMessages.Contains(message))
		request.AddMessage(message);
}

ChatResult result = await request.ExecuteAsync(false, cancellationToken);
ChatMessage? response;
```
```


### OS

Windows or Linux

### .Net version

.NET 8x

### Library version

3.3.11

**Comment by KeyserDSoze** [comment]
Now it works
